# name: URL Pinger

# on:
#   push:
#     branches:
#       - main           # Triggers when changes are pushed to the 'main' branch
#   schedule:
#     - cron: "*/10 * * * *"  # Runs every 10 minutes
#   workflow_dispatch:        # Allows manual triggering of the workflow

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up Python
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.x'

#       # Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests

#       # Run the Python script
#       - name: Run Test_backend.py
#         run: python3 Test_backend.py

name: URL Pinger

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script for 6 hours
        run: timeout 21600s python3 Test_backend.py  # Run for 6 hours (21600 seconds)

      - name: Trigger next workflow run
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/url_pinger.yml/dispatches \
          -d '{"ref":"main"}'

