# name: URL Pinger

# on:
#   push:
#     branches:
#       - main           # Triggers when changes are pushed to the 'main' branch
#   schedule:
#     - cron: "*/10 * * * *"  # Runs every 10 minutes
#   workflow_dispatch:        # Allows manual triggering of the workflow

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up Python
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.x'

#       # Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests

#       # Run the Python script
#       - name: Run Test_backend.py
#         run: python3 Test_backend.py
